###################################################################################
halyard:
  gitops:
    enabled: true
    repo:
      type: s3 
      s3accesskey: S3_ACCESS_KEY 
      s3secretkey: S3_SECRET_KEY 
      s3bucket: S3_BUCKET_NAME
      s3region: S3_BUCKET_REGION
    secretName: opsmx-gitops-auth
#####################################################################################
  image:
    repository: us-docker.pkg.dev/spinnaker-community/docker/halyard
    tag: 1.51.0
  additionalServiceSettings:
    gate.yml:
      healthEndpoint: /health
      kubernetes:
        useExecHealthCheck: false
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/gate:master-latest-unvalidated-ubuntu
    deck.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/deck:master-latest-unvalidated-ubuntu
    clouddriver-caching.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/clouddriver:master-latest-unvalidated-ubuntu
    clouddriver.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/clouddriver:master-latest-unvalidated-ubuntu
    clouddriver-rw.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/clouddriver:master-latest-unvalidated-ubuntu
    clouddriver-ro.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/clouddriver:master-latest-unvalidated-ubuntu
    clouddriver-ro-deck.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/clouddriver:master-latest-unvalidated-ubuntu
    echo.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/echo:master-latest-unvalidated-ubuntu
    echo-scheduler.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/echo:master-latest-unvalidated-ubuntu
    echo-worker.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/echo:master-latest-unvalidated-ubuntu
    fiat.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/fiat:master-latest-unvalidated-ubuntu
    front50.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/front50:master-latest-unvalidated-ubuntu
    igor.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/igor:master-latest-unvalidated-ubuntu
    kayenta.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/kayenta:master-latest-unvalidated-ubuntu
    orca.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/orca:master-latest-unvalidated-ubuntu
    rosco.yml:
      artifactId: us-docker.pkg.dev/spinnaker-community/docker/rosco:master-latest-unvalidated-ubuntu